export const simbolos_nbr = {
    'Frágil': '/fragil.webp',
    'Proibido Empilhar': '/proibido-empilhar.webp',
    'Proteger do Calor': '/proteger-contra-o-calor.webp',
    'Proteger da Luz': '/proteger-da-luz.webp',
    'Proteger da Umidade': '/protegerdaumidade.webp',
    'Corrosivo': '/corrosivo.webp',
    'Cargas Pesadas': '/cargas-pesadas.webp',
    'Explosivo': '/explosivo.webp',
    'Inflamável': '/inflamavel.webp',
    'Oxidante': '/oxidante.webp',
    'Risco Ambiental': '/risco-ambiental.webp',
    'Radioativo': '/radioativo.webp',
    'Gás Comprimido': '/gas-comprimido.webp',
}